---
abstract: "A simple client to TGC's web services."
author:
  - 'JT Smith <jt@plainblack.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TheGameCrafter-Client
requires:
  HTTP::Request::Common: 0
  JSON: 0
  LWP::UserAgent: 0
  Ouch: 0.0400
  Test::Deep: 0
  Test::More: 0
  URI: 0
resources:
  bugtracker: http://github.com/rizen/TheGameCrafter-Client/issues
  repository: git://github.com/rizen/TheGameCrafter-Client.git
version: 0.0102
